### ISSUE TITLE
Kogito Service displayName is duplicated at CSVs

### ISSUE THREAD

**Issue by bandrade** [kiegroup/kogito-cloud-operator#462]
While checking at OperatorHub, I found [two "Kogito Service"](https://pasteboard.co/JifoYwb.png) at Kogito Operator Details. It would be better if the respective Custom Resource have the same displayName.

https://github.com/kiegroup/kogito-cloud-operator/blob/master/deploy/olm-catalog/kogito-operator/0.12.0/kogito-operator.v0.12.0.clusterserviceversion.yaml#L119

https://github.com/kiegroup/kogito-cloud-operator/blob/master/deploy/olm-catalog/kogito-operator/0.12.0/kogito-operator.v0.12.0.clusterserviceversion.yaml#L660

https://github.com/kiegroup/kogito-cloud-operator/blob/master/deploy/olm-catalog/kogito-operator/0.13.0/kogito-operator.v0.13.0.clusterserviceversion.yaml#L119

https://github.com/kiegroup/kogito-cloud-operator/blob/master/deploy/olm-catalog/kogito-operator/0.13.0/kogito-operator.v0.13.0.clusterserviceversion.yaml#L660

**Comment by ricardozanini** [comment]
Thanks @bandrade! We're about to deprecate `KogitoApp`, so it wouldn't be available in CSV any more, it should be fixed in the upcoming 0.13 version in a couple of weeks.

**Comment by ricardozanini** [comment]
Opened [KOGITO-2813](https://issues.redhat.com/browse/KOGITO-2813) to track this

**Comment by bandrade** [comment]
Thanks @ricardozanini for the prompt response
