### ISSUE TITLE
Windows CLI Not Executable

### ISSUE THREAD

**Issue by jpgilchrist** [kiegroup/kogito-cloud-operator#500]
I attempted to follow instructions and downloaded the kogito cli from the release, but something about it seems off. Upon unzipping the archive it doesn't appear as an executable. Is there something that I'm missing? I don't see any extra info in the README. And every time I try to run `kogito new-project kogito-travel-agency` windows pops up the dialog that asks what app you want to run this in. 

![image](https://user-images.githubusercontent.com/5065660/89682749-42420000-d8c5-11ea-8804-f8f3b9795125.png)

**Comment by ricardozanini** [comment]
Hi! Thanks for bringing this to our attention. Looks like we've missed the file type. Could you try renaming it to `.exe`?
